### PR TITLE
macOS Support (based on `react-native-windows`)

### PR DESCRIPTION
**Pull request by mandrigin**
# Summary

This PR is based on the branch `macos-support` that already have been started.
It makes this version functional for `react-native-windows` applications.

No API changes are there.

I would love to get feedback on the code before I fix changelog (and, possibly, README.md)

### What's required for testing (prerequisites)?

macOS and `react-native-windows`.

### What are the steps to reproduce (after prerequisites)?

1. Create a sample app for macOS using `react-native-windows` (see [Getting Started](https://microsoft.github.io/react-native-windows/docs/0.62/rnm-getting-started) guide)

2. (due to a bug in RN itself) Go to macOS target settings and set "Dead Code Stripping" to `YES`.

3. `yarn add git@github.com:mandrigin/lottie-react-native.git#macos-support-2`

4. Add an animation to this app just like you normally do with Lottie.

5. `npx react-native run-macos` (you might have to run it twice because the metro bundler in RN macOS is started too late)

An example app, assuming that you have `a1.json` with your animation.
```javascript
import React from 'react';
import {
  SafeAreaView,
  StatusBar,
} from 'react-native';

import LottieView from 'lottie-react-native';


const App: () => React$Node = () => {
  return (
    <>
      <StatusBar barStyle="dark-content" />
      <SafeAreaView style={{backgroundColor: "grey", height: "100%"}}>
        <LottieView style={{width: 200, height: 200}} source={require('./a1.json')} loop autoPlay/>
      </SafeAreaView>
    </>
  );
};

export default App;
```

## Compatibility

n/a (experimental macOS support)

## Checklist

- [x] I have tested this on a device and a simulator
- [ ] I added the documentation in `README.md`
- [ ] I mentioned this change in `CHANGELOG.md`
- [x] I updated the typed files (TS and Flow)
- [x] I added a sample use of the API in the example project (`example/App.js`)

### CODE REVIEW

**Comment by emilioicai** [comment]
hey @mandrigin thanks for the PR. Unfortunately, this makes the build process crash on iOS. Did you test on an iOS app?

**Comment by mandrigin** [comment]
Yes, I tested on a simulator on iOS 13. Can you share the crash? I will try to reproduce and fix it.

**Comment by emilioicai** [comment]
Nevermind, it was a different issue, looks like everything is fine with the iOS implementation.

**Review by emilioicai — APPROVED** [review]

**Comment by mandrigin** [comment]
@emilioicai thanks! Is there anything else I should do except for waiting?

**Comment by mandrigin** [comment]
@emilioicai hey! I wanted to ping you about this pull request. I see you approved it but I can't merge it myself (I'm not a contributor). Do I need to get one more approval before this PR is merged?

**Comment by emilioicai** [comment]
@mandrigin no worries, everything seems to be fine codewise. It's just I want to make sure everything is fine building `lottie-react-native` with XCode12 before merging this in case we need to do an urgent release.

**Comment by mandrigin** [comment]
Ah, sure! iOS 14 and all its shenanigans...

**Comment by mandrigin** [comment]
@emilioicai hey! i wanted to ping about this PR? or is there any timeline for when it could be merged?

**Comment by mandrigin** [comment]
(I also have Windows support on the way...)

**Comment by tarasvakulka** [comment]
@mandrigin Thanks for mac os support, works fine. If you already have minimal working windows support, please make pull request.

**Comment by mandrigin** [comment]
@tarasvakulka here is the minimal Windows support: https://github.com/lottie-react-native/lottie-react-native/pull/700 The setup process is quite cumbersome, I tried to explain it. If you have any questions, ping me here.

**Comment by tarasvakulka** [comment]
> @tarasvakulka here is the minimal Windows support: #700 The setup process is quite cumbersome, I tried to explain it. If you have any questions, ping me here.

Thanks a lot, will try.

**Comment by mandrigin** [comment]
@tarasvakulka @emilioicai is there anything else that needs to be done to merge this PR? I'd love to get rid of our fork of `lottie-react-native` :-D

**Comment by tarasvakulka** [comment]
> @tarasvakulka @emilioicai is there anything else that needs to be done to merge this PR? I'd love to get rid of our fork of `lottie-react-native` :-D

I think this PR can be merge, all works fine)

**Comment by mandrigin** [comment]
Awesome! I don’t have permissions, so I have to ask someone from the core contributors to do that.

**Comment by emilioicai** [comment]
Hey, sorry for the late reply, this is a complex PR to test but I will try to have it properly tested during the week. Anyway, if you can find some more testers I think it would be really helpful :)

**Comment by mandrigin** [comment]
ah, okay... if you tell me which animations are good to test in it, I can try helping out too. We use a relatively simple animation at my current project, but it seems to all just work...

**Pull request merged**
