### PR TITLE
fix: DirectEvent to BubblingEvent on Android/Windows

### LINKED ISSUE #1221: Conflicts event type within Android/iOS/Windows
### Description

- TS uses `BubblingEventHandler`
https://github.com/lottie-react-native/lottie-react-native/blob/8e3969421e8a5ff2284d4cd833b4ca0534ee1e8a/packages/core/src/specs/LottieAnimationViewNativeComponent.ts#L57-L68

- Android uses `DirectEvent`
https://github.com/lottie-react-native/lottie-react-native/blob/8e3969421e8a5ff2284d4cd833b4ca0534ee1e8a/packages/core/android/src/main/java/com/airbnb/android/react/lottie/LottieAnimationViewManagerImpl.kt#L70-L80

- iOS uses `BubblingEvent`
https://github.com/lottie-react-native/lottie-react-native/blob/8e3969421e8a5ff2284d4cd833b4ca0534ee1e8a/packages/core/ios/LottieReactNative/LRNAnimationViewManagerObjC.m#L15-L17

- Windows CSharp uses `BubblingEvent`
https://github.com/lottie-react-native/lottie-react-native/blob/8e3969421e8a5ff2284d4cd833b4ca0534ee1e8a/packages/core/windows/LottieReactNativeWindows/LottieAnimationViewManager.cs#L153-L154

- Windows C++/WinRT uses `DirectEvent`
https://github.com/lottie-react-native/lottie-react-native/blob/8e3969421e8a5ff2284d4cd833b4ca0534ee1e8a/packages/core/windows/cppwinrt/LottieAnimationViewManager.cpp#L203-L209

### Steps to reproduce

none

### Snack or a link to a repository

none

### Lottie React Native version

6.7.2

### React Native version

0.73.1

### Platforms

Android, iOS, Windows

### Workflow

React Native

### Architecture

Paper (Old Architecture)

### Build type

None

### Device

None

### Acknowledgements

Yes

### PR DESCRIPTION
**Pull request by Sunbreak**
fix #1221

### CODE REVIEW

**Comment by TheRogue76** [comment]
Hey @Sunbreak. Sorry we haven't reviewed your PR. I will allocate some free time this weekend, make sure the Android setup is working good for new arch and old arch and either give feedback or approve and merge it.

**Comment by TheRogue76** [comment]
@Sunbreak Checked on Android in Fabric, the events do not seem to be sent anymore:
Screenshot 2024-05-04 at 09 42 23

**Review by TheRogue76 — CHANGES_REQUESTED** [review]
Seems to have been broken on Android

**Comment by Sunbreak** [comment]
Or BubblingEvent to DirectEvent on iOS?

**Comment by TheRogue76** [comment]
> Or BubblingEvent to DirectEvent on iOS?

Come to think of it, maybe it should all be direct events, even for iOS and in the spec. The point of Bubbling event was that we had some weird setup where the custom view of Lottie was wrapped by another view, but now that it is gone, maybe the spec should change and it should all become direct event, cause we are capturing it there directly. Try it out, let me know how it works.

**Comment by TheRogue76** [comment]
Any updates @Sunbreak ?

**Pull request closed without merging**
