### PR TITLE
Windows support [C#]

### PR DESCRIPTION
**Pull request by mandrigin**
It is based on the macOS support: #679

## How to run it

Create a react-native-windows app **in C#** see [this doc](https://microsoft.github.io/react-native-windows/docs/getting-started), use `npx react-native-windows-init --overwrite --language cs`

Add `lottie-react-native` to deps: `yarn add`

Add `node_modules/lottie-react-native/src/windows/LottieReactNativeWindows/LottieReactNativeWindows.csproj` to the solution.

Add `LottieReactNativeWindows` project to the references of the main project.

Add the following to the main project's `App.xaml.cs` to the constructor.

```cs
PackageProviders.Add(new LottieReactNativeWindows.ReactPackageProvider());
```

Now you can use LottieView!

## Using CodeGen & Color Filters

Windows version allows using codegen files: https://docs.microsoft.com/en-us/windows/communitytoolkit/animations/lottie-scenarios/getting_started_codegen

That is the only way to make sure that the colors change.

That is the example on how to use that:

```javascript

<LottieView
          style={{width: 600, height: 600}}
          source="codegen://LottieWindowsDemoApp.AnimatedVisuals.Data"
          loop
          autoPlay
          colorFilters={[
            {keypath: "PlayPauseColor", color: "#ABABAB"},
          ]}
/>
```

Where `LottieWindowsDemoApp.AnimatedVisuals.Data` is the identifier of the class generated by the codegen utility and `PlayPauseColor` is a special name of the layer supported by the codegen utility.

This code of course assumes that the class `Data` in namespace `AnimatedVisuals` is added to your project that is named `LottieWindowsDemoApp`.

### CODE REVIEW

**Comment by tarasvakulka** [comment]
@mandrigin I get error when try to build (see screenshot). I create RN project from scratch and do all your installation instruction.
photo_2020-11-11 20 14 27

"lottie-react-native-windows": "git+https://github.com/mandrigin/lottie-react-native-1.git#windows-support-csharp",
 "react": "16.11.0",
 "react-native": "^0.62.0-0",
 "react-native-windows": "^0.62.0-0"

**Comment by mandrigin** [comment]
Hmm, try manually adding ReactNative and ReactNative.Managed to the references of LottieAnimationView project

**Comment by tarasvakulka** [comment]
> Hmm, try manually adding ReactNative and ReactNative.Managed to the references of LottieAnimationView project

I added ReactNative.Managed see screenshot (screen_vs_studio.jpg) and check if I do this right. After this I try to build, but I get new error when try  to build see screenshot (screen_error.jpg).
screen_vs_studio
screen_error

**Comment by mandrigin** [comment]
Ah, sorry, I think it is because you use react-native-windows 0.62 and this code supports 0.63

**Comment by tarasvakulka** [comment]
> Ah, sorry, I think it is because you use react-native-windows 0.62 and this code supports 0.63

Can I do fix for 0.62 ? Because I need 0.62 version for mac os, I can't use 0.63

**Comment by mandrigin** [comment]
> > Ah, sorry, I think it is because you use react-native-windows 0.62 and this code supports 0.63
> 
> Can we do fix for 0.62 ? Because I need 0.62 version for mac os, I can't use 0.63

That’s a bit weird but there will be version parity soon. Right now we have to have different versions for Mac and windows.

I can try to look into 0.62 later on but I hope it soon will be unnecessary.

**Comment by tarasvakulka** [comment]
> > > Ah, sorry, I think it is because you use react-native-windows 0.62 and this code supports 0.63
> > 
> > 
> > Can we do fix for 0.62 ? Because I need 0.62 version for mac os, I can't use 0.63
> 
> That’s a bit weird but there will be version parity soon. Right now we have to have different versions for Mac and windows.
> 
> I can try to look into 0.62 later on but I hope it soon will be unnecessary.

Got it, thanks.

**Comment by tarasvakulka** [comment]
@mandrigin I create new project with RN 0.63.2, do all your installation instruction, but still can't build. Please, help.
photo_2020-11-11 23 42 33

**Comment by mandrigin** [comment]
does it happen when you are doing `npx react-native run-windows`?

**Comment by mandrigin** [comment]
if you have a Visual Studio, it might help if you try building from there... or if you can share the project itself on github somewhere... I haven't seen these errors myself, I assume that they are something to do with the build environment.

**Comment by mandrigin** [comment]
there is this article about all the necessary dependencies: https://microsoft.github.io/react-native-windows/docs/rnw-dependencies#windows-development-dependencies

**Comment by tarasvakulka** [comment]
> does it happen when you are doing `npx react-native run-windows`?

Yes

**Comment by mandrigin** [comment]
@tarasvakulka can you check that your system is setup according to the article Ove shared?

**Comment by tarasvakulka** [comment]
> @tarasvakulka can you check that your system is setup according to the article I’ve shared?

I checked, all the necessary dependencies installed. @mandrigin May be problem in Microsoft.ReactNative.Manged.CodeGen, because when I try to add reference on it to my project in VS, I can't do it VS give me error alert?

**Comment by mandrigin** [comment]
> > @tarasvakulka can you check that your system is setup according to the article I’ve shared?
> 
> I checked, all the necessary dependencies installed. @mandrigin May be problem in Microsoft.ReactNative.Manged.CodeGen, because when I try to add reference on it to my project in VS, I can't do it VS give me error alert?

You don’t need Managed.CodeGen dependency I think. What if you try building the solution in VS?

**Comment by mandrigin** [comment]
btw, you can ping me at t.me/mandrigin for more real-time debugging... I can’t reproduce that error on my machine...

**Comment by tarasvakulka** [comment]
> > > @tarasvakulka can you check that your system is setup according to the article I’ve shared?
> > 
> > 
> > I checked, all the necessary dependencies installed. @mandrigin May be problem in Microsoft.ReactNative.Manged.CodeGen, because when I try to add reference on it to my project in VS, I can't do it VS give me error alert?
> 
> You don’t need Managed.CodeGen dependency I think. What if you try building the solution in VS?

I will try bit later.

**Comment by tarasvakulka** [comment]
> btw, you can ping me at t.me/mandrigin for more real-time debugging... I can’t reproduce that error on my machine...

Thanks a lot, I will create repo with my code, and ping you.

**Comment by tarasvakulka** [comment]
> btw, you can ping me at t.me/mandrigin for more real-time debugging... I can’t reproduce that error on my machine...

This is -> https://github.com/tarasvakulka/TestRnWindows my project. You can try to build and reproduce error on your machine.

**Comment by mandrigin** [comment]
I will try tomorrow. I’m in CET, it’s bit early here. I would love it to be merged, so I’m ready to fix whatever needed :)

**Comment by tarasvakulka** [comment]
> > > @tarasvakulka can you check that your system is setup according to the article I’ve shared?
> > 
> > 
> > I checked, all the necessary dependencies installed. @mandrigin May be problem in Microsoft.ReactNative.Manged.CodeGen, because when I try to add reference on it to my project in VS, I can't do it VS give me error alert?
> 
> You don’t need Managed.CodeGen dependency I think. What if you try building the solution in VS?

I'm try to build solution, but get the same error (see screenshot, sorry for not english VS).
Ошибка    файл ресурсов "D:\Projects\SavePirateWindows\node_modules\react-native-windows\Microsoft.ReactNative.Managed.CodeGen\obj\project.assets.json" не содержит целевого объекта для "netcoreapp3.1". Проверьте, что восстановление выполнено и вы включили "netcoreapp3.1" в TargetFrameworks своего проекта.  SavePirateWindows
vs_buid

**Comment by mandrigin** [comment]
@tarasvakulka your project works on my machine when I compile in VS

1. `git clone https://github.com/tarasvakulka/TestRnWindows.git`

2. `cd TestRnWindows`

3. `.\windows\SavePirateWindows.sln` <- opens VS

4. `npx react-native start` <- in PowerShell

5. In VS select x64 and press "Debug -> Start Debugging (F5)".

**Comment by tarasvakulka** [comment]
> @tarasvakulka your project works on my machine when I compile in VS
> 
> 1. `git clone https://github.com/tarasvakulka/TestRnWindows.git`
> 2. `cd TestRnWindows`
> 3. `.\windows\SavePirateWindows.sln` <- opens VS
> 4. `npx react-native start` <- in PowerShell
> 5. In VS select x64 and press "Debug -> Start Debugging (F5)".
> 
> 

It's great, but how I can fix my error "Check that the restore is complete and you have included "netcoreapp3.1" in the TargetFrameworks of your project"? How and where I can add "netcoreapp3.1"?

**Comment by mandrigin** [comment]
I'm running
```
Microsoft Visual Studio Community 2019
Version 16.7.4
VisualStudio.16.Release/16.7.4+30517.126
Microsoft .NET Framework
Version 4.8.04084

Installed Version: Community

Visual C++ 2019   00435-60000-00000-AA547
Microsoft Visual C++ 2019

ASP.NET and Web Tools 2019   16.7.532.28833
ASP.NET and Web Tools 2019

Azure App Service Tools v3.0.0   16.7.532.28833
Azure App Service Tools v3.0.0

C# Tools   3.7.0-6.20459.4+7ee7c540e3bf19765695b1331c946ddf986d1516
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Extensibility Message Bus   1.2.6 (master@34d6af2)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

Mono Debugging for Visual Studio   16.7.5 (112c7bc)
Support for debugging Mono processes with Visual Studio.

Node.js Tools   1.5.20701.1 Commit Hash:b0da3724234b78593207434292d9f891440edea1
Adds support for developing and debugging Node.js apps in Visual Studio

NuGet Package Manager   5.7.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Test Adapter for Boost.Test   1.0
Enables Visual Studio's testing tools with unit tests written for Boost.Test.  The use terms and Third Party Notices are available in the extension installation directory.

Test Adapter for Google Test   1.0
Enables Visual Studio's testing tools with unit tests written for Google Test.  The use terms and Third Party Notices are available in the extension installation directory.

TypeScript Tools   16.0.20702.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   3.7.0-6.20459.4+7ee7c540e3bf19765695b1331c946ddf986d1516
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools 10.10.0.0 for F# 4.7   16.7.0-beta.20361.3+3ef6f0b514198c0bfa6c2c09fefe41a740b024d5
Microsoft Visual F# Tools 10.10.0.0 for F# 4.7

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Tools for CMake   1.0
Visual Studio Tools for CMake

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Foo   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   16.7.000.452 (d16-7@033b1a7)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   16.7.0.495 (remotes/origin/d16-7@79c0c522c)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   16.7.85 (1bcbbdf)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   11.0.2.0 (d16-7/025fde9)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: 83105ba
    Java.Interop: xamarin/java.interop/d16-7@1f3388a
    ProGuard: Guardsquare/proguard/proguard6.2.2@ebe9000
    SQLite: xamarin/sqlite/3.32.1@1a3276b
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-7@017078f


Xamarin.iOS and Xamarin.Mac SDK   14.0.0.0 (7ec3751a1)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.
```

**Comment by mandrigin** [comment]
@tarasvakulka which version of VS do you have?

**Comment by mandrigin** [comment]
Also I don't know if that is related, but I noticed that you have both package-lock.json from `npm` and also `yarn.lock` from `yarn`. That might lead to unexpected library versioning. Try to only use `yarn` and see how it goes. Delete your `node_modules` and try to run `yarn install`.

**Comment by tarasvakulka** [comment]
> @tarasvakulka which version of VS do you have?

Microsoft Visual Studio Community 2019
Версия 16.8.0
VisualStudio.16.Release/16.8.0+30709.132
Microsoft .NET Framework
Версия 4.8.04084

Установленная версия: Community

Visual C++ 2019   00435-60000-00000-AA193
Microsoft Visual C++ 2019

ASP.NET and Web Tools 2019   16.8.550.19892
ASP.NET and Web Tools 2019

ASP.NET Core Razor Language Services   16.1.0.2052803+84e121f1403378489b842e1797df2f3f5a49ac3c
Provides languages services for ASP.NET Core Razor.

ASP.NET Web Frameworks and Tools 2019   16.8.550.19892
Дополнительные сведения см. на веб-сайте https://www.asp.net/

Azure Functions and Web Jobs Tools   16.8.550.19892
Azure Functions and Web Jobs Tools

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

SQL Server Data Tools   16.0.62010.06180
Microsoft SQL Server Data Tools

Test Adapter for Boost.Test   1.0
Enables Visual Studio's testing tools with unit tests written for Boost.Test.  The use terms and Third Party Notices are available in the extension installation directory.

Visual Studio Container Tools Extensions   1.0
Просмотр, диагностика контейнеров в Visual Studio и управление ими.

Visual F# Tools   16.8.0-beta.20507.4+da6be68280c89131cdba2045525b80890401defd
Microsoft Visual F# Tools

Адаптер теста для Google Test   1.0
Включает средства тестирования Visual Studio и модульные тесты для Google Test.  Условия использования и уведомления сторонних производителей см. в каталоге установки расширения.

Диспетчер пакетов NuGet   5.8.0
Диспетчер пакетов NuGet в Visual Studio. Дополнительные сведения о NuGet см. на веб-сайте https://docs.nuget.org/

Инструменты C#   3.8.0-5.20519.18+4c195c3ac1974edcefa76774d7a59a2350ec55fa
Компоненты C#, используемые в интегрированной среде разработки. В зависимости от типа и настроек проекта могут использоваться различные версии компилятора.

Инструменты Microsoft Azure   2.9
Microsoft Azure Tools для Microsoft Visual Studio 2019 — версия 2.9.30924.1

Инструменты Visual Basic   3.8.0-5.20519.18+4c195c3ac1974edcefa76774d7a59a2350ec55fa
Компоненты Visual Basic, используемые в интегрированной среде разработки. В зависимости от типа и настроек проекта могут использоваться различные версии компилятора.

Инструменты Visual Studio для CMake   1.0
Инструменты Visual Studio для CMake

Инструменты непрерывной поставки Microsoft для Visual Studio   0.4
Упрощение настройки конвейеров Azure DevOps из интегрированной среды разработки Visual Studio.

Мастера Microsoft Visual C++   1.0
Мастера Microsoft Visual C++

Общие инструменты Windows Azure   1.10
Предоставляет общие службы для использования мобильными службами и инструментами Microsoft Azure.

Пакет VC Microsoft Visual Studio   1.0
Пакет VC Microsoft Visual Studio

Пакет размещения адаптеров отладки Visual Studio Code   1.0
Уровень взаимодействия для размещения адаптеров отладки Visual Studio Code в Visual Studio

Расширение IntelliCode   1.0
Подробные сведения о расширении IntelliCode для Visual Studio

Средства Microsoft Visual Studio для контейнеров   1.1
Разработка, запуск и проверка приложений ASP.NET Core в целевой среде. Нажав клавишу F5, можно отправить приложение напрямую в контейнер с отладкой, а клавиши CTRL+F5 позволяют изменить и обновить приложение без повторной сборки контейнера.

Средства TypeScript   16.0.21016.2001
Средства TypeScript для Microsoft Visual Studio

Средства Visual Studio для контейнеров   1.0
Средства Visual Studio для контейнеров

Средства Службы приложений Azure, версия 3.0.0   16.8.550.19892
Средства Службы приложений Azure, версия 3.0.0

**Comment by tarasvakulka** [comment]
> Also I don't know if that is related, but I noticed that you have both package-lock.json from `npm` and also `yarn.lock` from `yarn`. That might lead to unexpected library versioning. Try to only use `yarn` and see how it goes. Delete your `node_modules` and try to run `yarn install`.

Ok, few minutes.

**Comment by mandrigin** [comment]
I found a "bug" in my project setup similar to this one: https://github.com/microsoft/react-native-windows/issues/6239 and just fixed it.

**Comment by mandrigin** [comment]
quotes because it is just ms changed the project setup for libraries in one of the updates

**Comment by tarasvakulka** [comment]
> I found a "bug" in my project setup similar to this one: [microsoft/react-native-windows#6239](https://github.com/microsoft/react-native-windows/issues/6239) and just fixed it.

It can cause my error when I build solution or not?

**Comment by mandrigin** [comment]
It fixes another error when it tries to run the built app. In your case, it didn't even reach that.
Did you try to remove node_modules and re-download again with yarn?

**Comment by tarasvakulka** [comment]
> It fixes another error when it tries to run the built app. In your case, it didn't even reach that.
> Did you try to remove node_modules and re-download again with yarn?

@mandrigin Man, you made my day, I reinstall node_modules, build project and all works fine!

**Comment by tarasvakulka** [comment]
@mandrigin Could you tell me please, can i put my json files for animations in native side for windows? What folder name it's? Also what is folder name for png files (that i use in my lottie animation) in native side for windows?

**Comment by mandrigin** [comment]
@tarasvakulka I remember that Lottie for windows doesn't support external PNGs, just the ones that are built-in (when you export from AfterEffect, it can encode those PNGs into base64 inside the JSON file).

Let me come back to you about the exact folder. If I remember correctly, you just need to add JSON files to the project and setup "copy to the output dir" or something like that... I'll check it today. We ourselves in our project use `codegen`-ed version actively instead of JSON files directly.

**Comment by tarasvakulka** [comment]
> Lottie for windows doesn't support external PNGs

Looking forward to your response about json files, I try bit later too.
About external png, I see pull request https://github.com/windows-toolkit/Lottie-Windows/pull/111, could you explain me please, is it bring external png support for windows or not? Because I have a lot of json files that use external png files, and I don't now what right way to choose, because export from AfterEffect with encode all PNGs into base64, might will make my json files very heavy and with bad perfomance, what you think about it?

**Comment by mandrigin** [comment]
@tarasvakulka as far as I know it was only for codegen files. In my case, the json files weren't that big (about 1-2 MB for a huge animation) and I didn't see performance degradation. It is running on a desktop machine after all.

The current version needs you to put json files into `Assets` directory in Visual Studio, then set their type to "Content" and behaviour to "Copy Always".

Then you can address them like that `<LottieView source="aspx:///Assets/myAnimation.json" />`.

I will fix it to remove the need for `aspx://Assets/` now.

**Comment by mandrigin** [comment]
@tarasvakulka updated. With the latest commit, you can just put your file `myAnimation.json` to the `Assets` folder, do the same dance with `Content`/`Copy Always` and then just specify `<LottieView source="myAnimation.json" />` and it should work.

**Comment by tarasvakulka** [comment]
> @tarasvakulka updated. With the latest commit, you can just put your file `myAnimation.json` to the `Assets` folder, do the same dance with `Content`/`Copy Always` and then just specify `<LottieView source="myAnimation.json" />` and it should work.

Thanks)

**Comment by tarasvakulka** [comment]
@mandrigin Could you please explain once more, for my case when I have a lot of json files where each item use 5-7 png files, what the right way re-export from AfterEffect with encode all PNGs into base64 or may be use codgen can solve my problem with external png for my lottie-animations?

**Comment by mandrigin** [comment]
@tarasvakulka i think in your case (many animations that reuse the same png files the CodeGen is the best approach. In general, it’s the one recommended on Windows, because you don’t have to parse anything and also you can use dynamic colors there.

**Comment by tarasvakulka** [comment]
> @tarasvakulka i think in your case (many animations that reuse the same png files the CodeGen is the best approach. In general, it’s the one recommended on Windows, because you don’t have to parse anything and also you can use dynamic colors there.

Thanks, I understand correctly that when I generate c# class from my json, I can easily add a path to my png files in generated .cs file?

**Comment by mandrigin** [comment]
I think CodeGen will generate it automatically, you might have to specify the folder with the png files. But I think it defaults to Assets.

**Comment by tarasvakulka** [comment]
> I think CodeGen will generate it automatically, you might have to specify the folder with the png files. But I think it defaults to Assets.

Understood, thanks again)

**Review by emilioicai — APPROVED** [review]

**Comment by emilioicai** [comment]
hey @mandrigin this looks good to me, thanks a lot for the big effort. Could you help me with the documentation though?

**Comment by mandrigin** [comment]
@emilioicai sure! I'm sick now, maybe in a week or two I'll have some time to help.

**Comment by emilioicai** [comment]
@mandrigin sure! no worries, I know we took a lot of time to review this so take your time to get well!

**Comment by mandrigin** [comment]
@emilioicai I'm finally recovered from my covid. How can I help you with the documentation?

**Comment by emilioicai** [comment]
@mandrigin great to hear you are recovered! We would need to add some bits of documentation to the README explaining how to setup an run a project with windows support. A brief example should be sufficient for it..

**Pull request merged**
