### PR TITLE
update README.md to a modern syntax

### PR DESCRIPTION
**Pull request by andresribeiro**

### CODE REVIEW

**Review by flexbox — APPROVED** [review]
Sounds Good To Me 🚀

**Comment by andresribeiro** [comment]
@flexbox done

**Comment by flexbox** [comment]
Nice!

@emilioicai it seams we can merge it :)

**Review by emilioicai — APPROVED** [review]

**Comment by emilioicai** [comment]
Thanks guys!

**Comment by Ak4ts** [comment]
Amazing!!!

**Pull request merged**
