### PR TITLE
Fix React dependency so XCode 12 can compile

### PR DESCRIPTION
**Pull request by harunsmrkovic**
# Summary

Fixes issue described in https://github.com/facebook/react-native/issues/29633

### What's required for testing (prerequisites)?

No tests needed, it was a wrong dependency.

## Compatibility

| OS      | Implemented |
| ------- | :---------: |
| iOS     |    ✅     |
| Android |    ✅     |

## Checklist

- [x] I have tested this on a device and a simulator
- [ ] I added the documentation in `README.md`
- [ ] I mentioned this change in `CHANGELOG.md`
- [ ] I updated the typed files (TS and Flow)
- [ ] I added a sample use of the API in the example project (`example/App.js`)

### CODE REVIEW

**Comment by mburnet6-ibm** [comment]
@harunsmrkovic I tried applying this locally and got an error during `pod install`.

```
[!] The following Swift pods cannot yet be integrated as static libraries:

The Swift pod `lottie-react-native-iOS` depends upon `React-Core-iOS`, which does not define modules. To opt into those targets generating module maps (which is necessary to import them from Swift when building as static libraries), you may set `use_modular_headers!` globally in your Podfile, or specify `:modular_headers => true` for particular dependencies.
```

can you share how you have your Podfile setup to make this work?

**Comment by harunsmrkovic** [comment]
Hm, it could be that `use_frameworks!` gets rids of this error for me... Not sure, haven't seen that error in awhile...

**Comment by emilioicai** [comment]
`lottie-react-native` is a Swift module, if we merge this PR we will start having this issue: https://github.com/facebook/react-native/issues/29633#issuecomment-694700346

We are waiting for a change in React Core's podspec to fix the issue: https://github.com/facebook/react-native/pull/29995

**Comment by emilioicai** [comment]
Looks like the change in React Core is already merged. Can anybody help me here testing this before merging?

**Review by emilioicai — APPROVED** [review]

**Comment by emilioicai** [comment]
This has been resolved on https://github.com/lottie-react-native/lottie-react-native/pull/738

**Pull request closed without merging**
