### PR TITLE
fix: react native macos build

### PR DESCRIPTION
**Pull request by matinzd**
Fixes: https://github.com/lottie-react-native/lottie-react-native/issues/1018

### CODE REVIEW

**Comment by Saadnajmi** [comment]
> /cc @Saadnajmi

Do we have a way to test macOS? What we've done in other repos is move the test app to use this (https://github.com/microsoft/react-native-test-app). That way, it is easy to add out of tree platforms like macOS and windows without needing to worry about maintaining extra boilerplate code.

**Comment by matinzd** [comment]
> > /cc @Saadnajmi
> 
> Do we have a way to test macOS? What we've done in other repos is move the test app to use this (https://github.com/microsoft/react-native-test-app). That way, it is easy to add out of tree platforms like macOS and windows without needing to worry about maintaining extra boilerplate code.

Yeah this is what I was trying to go for but we somehow decided to not go with it that time.
Maybe it's a good time to move to RNTA.

**Review by emilioicai — APPROVED** [review]

**Comment by Saadnajmi** [comment]
Awesome! :D

**Pull request merged**
